Check if the platform supports atomics operations, else add -latomic to the link flags
Debian failed to build the version 1.0~rc1 on armel mipsel m68k and sh4,
where it used to build fine until the version 1.0~beta2.

The failure would be:
[100%] Linking CXX executable ../bin/inkview
cd "/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/src" && /usr/bin/cmake -E cmake_link_script CMakeFiles/inkview.dir/link.txt --verbose=1
/usr/bin/c++  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Werror=format -Werror=format-security -pthread -fopenmp  -Wl,-z,relro -Wl,-z,now -rdynamic CMakeFiles/inkview.dir/inkview-main.cpp.o  -o ../bin/inkview  -Wl,-rpath,"/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/lib/arm-linux-gnueabi:" ../lib/arm-linux-gnueabi/libinkscape_base.so -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lharfbuzz -lfontconfig -lfreetype -lgsl -lgslcblas -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -llcms2 -lc -lgc -lpoppler -lpoppler-glib -lcairo -lwpg-0.3 -lrevenge-0.0 -lrevenge-stream-0.0 -lvisio-0.1 -lcdr-0.1 -ljpeg -lpng -lpotrace -ldbus-glib-1 -ldbus-1 -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lcairomm-1.0 -lsigc-2.0 -lgdl-3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtkspell3-3 -lgtk-3 -lgdk-3 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lenchant-2 -lxslt -lxml2 -lz -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lsigc-2.0 -lSM -lICE -lX11 -lXext
/usr/bin/ld: ../lib/arm-linux-gnueabi/libinkscape_base.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../lib/arm-linux-gnueabi/libinkscape_base.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/inkview.dir/build.make:109: bin/inkview] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi'
make[2]: *** [CMakeFiles/Makefile2:2483: src/CMakeFiles/inkview.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../bin/inkscape
cd "/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/src" && /usr/bin/cmake -E cmake_link_script CMakeFiles/inkscape.dir/link.txt --verbose=1
/usr/bin/c++  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Werror=format -Werror=format-security -pthread -fopenmp  -Wl,-z,relro -Wl,-z,now -rdynamic CMakeFiles/inkscape.dir/inkscape-main.cpp.o  -o ../bin/inkscape  -Wl,-rpath,"/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/lib/arm-linux-gnueabi:" ../lib/arm-linux-gnueabi/libinkscape_base.so -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lharfbuzz -lfontconfig -lfreetype -lgsl -lgslcblas -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -llcms2 -lc -lgc -lpoppler -lpoppler-glib -lcairo -lwpg-0.3 -lrevenge-0.0 -lrevenge-stream-0.0 -lvisio-0.1 -lcdr-0.1 -ljpeg -lpng -lpotrace -ldbus-glib-1 -ldbus-1 -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lcairomm-1.0 -lsigc-2.0 -lgdl-3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtkspell3-3 -lgtk-3 -lgdk-3 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lenchant-2 -lxslt -lxml2 -lz -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lsigc-2.0 -lSM -lICE -lX11 -lXext
/usr/bin/ld: ../lib/arm-linux-gnueabi/libinkscape_base.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../lib/arm-linux-gnueabi/libinkscape_base.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/inkscape.dir/build.make:109: bin/inkscape] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi'
make[2]: *** [CMakeFiles/Makefile2:2510: src/CMakeFiles/inkscape.dir/all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabi'

Signed-off-by: Mattia Rizzolo <mattia@mapreri.org>


(cherry picked from commit 841438f418a7d6ff4bd79b1b527271046272da72)